CREATE TABLE `token` (
  `id` varchar(100) NOT NULL,
  `userID` varchar(100) NOT NULL,
  `services_read` varchar(100) DEFAULT 'deny',
  `services_write` varchar(100) DEFAULT 'deny',
  `deals_write` varchar(100) DEFAULT 'deny',
  `deals_read` varchar(100) DEFAULT 'deny',
  `org_read` varchar(100) DEFAULT 'deny',
  `org_write` varchar(100) DEFAULT 'deny',
  `users_read` varchar(100) DEFAULT 'deny',
  `users_write` varchar(100) DEFAULT 'deny',
  `token_read` varchar(100) DEFAULT 'deny',
  `token_write` varchar(100) DEFAULT 'deny',
  UNIQUE KEY `userID_UNIQUE` (`userID`),
  KEY `fk_s_read_idx` (`services_read`),
  KEY `fk_s_write_idx` (`services_write`),
  KEY `fk_u_read_idx` (`users_read`),
  KEY `fk_u_write_idx` (`users_write`),
  KEY `fk_d_write_idx` (`deals_write`),
  KEY `fk_d_read_idx` (`deals_read`),
  KEY `fk_t_read_idx` (`token_read`),
  KEY `fk_t_write_idx` (`token_write`),
  KEY `fk_o_read_idx` (`org_read`),
  KEY `fk_o_write_idx` (`org_write`),
  CONSTRAINT `fk_deals_read` FOREIGN KEY (`deals_read`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_deals_write` FOREIGN KEY (`deals_write`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_org_read` FOREIGN KEY (`org_read`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_org_write` FOREIGN KEY (`org_write`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_services_read` FOREIGN KEY (`services_read`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_services_write` FOREIGN KEY (`services_write`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_token_read` FOREIGN KEY (`token_read`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_token_write` FOREIGN KEY (`token_write`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_userID` FOREIGN KEY (`userID`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_users_read` FOREIGN KEY (`users_read`) REFERENCES `permissions` (`id`),
  CONSTRAINT `fk_users_write` FOREIGN KEY (`users_write`) REFERENCES `permissions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
